import type { Metadata } from 'next';
import Link from 'next/link';
import { Masthead, Footer } from '@/components/Chrome';

export const metadata: Metadata = {
  title: 'Privacy | Squarespell Site Auditor',
  description: 'What the Squarespell Site Auditor stores, why, and how to have it removed.',
};

export default function PrivacyPage() {
  return (
    <>
      <Masthead />
      <main>
        <div className="frame">
          <article className="doc">
            <p className="crumb">
              <Link href="/">Squarespace site auditor</Link>
            </p>
            <h1>Privacy</h1>
            <p className="doc-lede">
              Short version: we store the audit, and we store your email only if you choose to give it.
            </p>

            <div className="doc-part">
              <h2>When you run an audit</h2>
              <p>
                We store the website address you entered, the technical findings, the score, and how long
                the audit took. We also store a one-way hash of your IP address and browser user agent.
                That hash is used to apply rate limits and detect abuse. We do not store the IP address
                itself, and the hash cannot be reversed to recover it.
              </p>
              <p>
                If you arrive from a campaign link we store the UTM parameters in the URL and the referring
                page, so we know which channels bring people to the tool.
              </p>
              <p>
                Each audit gets a share link. Anyone with that link can view that report, so only share it
                with people you want to see it. Share links are not listed anywhere and are excluded from
                search engines.
              </p>
            </div>

            <div className="doc-part">
              <h2>When you give us your email</h2>
              <p>
                The contact form is optional and appears after the full report. If you use it we store your
                email address, your name if you give one, the website you audited, and what you said you
                wanted help with. We use that to reply to you.
              </p>
              <p>
                The marketing checkbox is separate and unticked by default. If you leave it unticked we
                will not add you to any mailing list.
              </p>
            </div>

            <div className="doc-part">
              <h2>What we do not do</h2>
              <p>
                We do not sell or share your data with third parties. We do not run advertising trackers or
                cross-site pixels on this tool. We do not store the contents of your website beyond the
                specific extracts shown as evidence in your report.
              </p>
            </div>

            <div className="doc-part">
              <h2>AI</h2>
              <p>
                The written explanations in a report may be generated by an AI model. The model receives
                only the structured findings our own engine measured, never your raw page content, and
                never your personal details.
              </p>
            </div>

            <div className="doc-part">
              <h2>Removing your data</h2>
              <p>
                Email <a href="mailto:info@squarespell.com">info@squarespell.com</a> and we will delete
                your audits, your share links and your contact record. No conditions attached.
              </p>
            </div>
          </article>
        </div>
      </main>
      <Footer />
    </>
  );
}
