/**
 * Local stand-in for the Anthropic Messages API. The real @anthropic-ai/sdk
 * talks to it through ANTHROPIC_BASE_URL, so timeouts/retries are the SDK's.
 */
import http from 'http';
import type { AddressInfo } from 'net';

export type StubMode = 'ok' | 'http500' | 'http429' | 'hang' | 'garbage';

export const anthropicStub = {
  mode: 'ok' as StubMode,
  calls: 0,
  reply: null as null | (() => string),
  reset() { this.mode = 'ok'; this.calls = 0; this.reply = null; },
};

const defaultQuiz = () => JSON.stringify({
  title: 'Stub Generated Quiz',
  description: 'generated by local stub',
  questions: Array.from({ length: 3 }, (_, i) => ({
    id: 'q' + (i + 1), text: 'Question ' + (i + 1), type: 'single',
    options: [0, 1, 2, 3].map((n) => ({ id: 'o' + n, text: 'Option ' + n, score: n })),
  })),
  outcomes: [
    { id: 'r1', title: 'Low', description: 'low', minScore: 0, maxScore: 3 },
    { id: 'r2', title: 'High', description: 'high', minScore: 4, maxScore: 9 },
  ],
});

export function startAnthropicStub(): Promise<string> {
  const server = http.createServer((req, res) => {
    req.resume();
    req.on('end', () => {
      anthropicStub.calls++;
      const mode = anthropicStub.mode;
      if (mode === 'hang') return; // never answer
      if (mode === 'http500' || mode === 'http429') {
        res.writeHead(mode === 'http500' ? 500 : 429, { 'content-type': 'application/json' });
        return res.end(JSON.stringify({ type: 'error', error: { type: mode === 'http500' ? 'api_error' : 'rate_limit_error', message: 'stub failure' } }));
      }
      const text = mode === 'garbage' ? 'this is not json at all' : (anthropicStub.reply ? anthropicStub.reply() : defaultQuiz());
      res.writeHead(200, { 'content-type': 'application/json' });
      res.end(JSON.stringify({
        id: 'msg_stub', type: 'message', role: 'assistant', model: 'stub', stop_reason: 'end_turn',
        content: [{ type: 'text', text }], usage: { input_tokens: 1, output_tokens: 1 },
      }));
    });
  });
  server.unref();
  return new Promise((resolve) => server.listen(0, '127.0.0.1', () => resolve(`http://127.0.0.1:${(server.address() as AddressInfo).port}`)));
}
