/**
 * Squarespace-specific checks.
 *
 * These are the findings a generic site auditor cannot produce, and they are
 * the reason this tool exists. Every one is derived from a Squarespace-specific
 * behaviour verified against live sites.
 */

import { AuditContext, count, fail, finding, na, pass, truncate, verb } from '../context';
import type { CheckResult } from '../types';
import { pathOf } from '../url';

const DEFAULT_FAVICON = 'assets.squarespace.com/universal/default-favicon.ico';

/**
 * Whether a URL path's last segment looks like a Squarespace auto-generated
 * slug rather than one a human chose.
 *
 * The previous version flagged anything on length alone (20+ alphanumeric
 * characters with no separators), which catches a legitimate long compound
 * slug a human deliberately chose (a German compound word, a product SKU, or
 * a deliberately long keyword slug like "customweddinginvitationdesign
 * service") just as readily as real gibberish. Squarespace's actual
 * auto-generated slugs are random and mix letters with scattered digits;
 * a human-chosen slug, however long, is almost always either all letters or
 * carries one short, meaningful number (a year, a model number), not digits
 * scattered throughout (AUDIT-OF-THE-AUDIT.md, Step 3, SQS-008).
 */
function looksAutoGenerated(segment: string): boolean {
  if (segment.length < 12) return false;
  const digitCount = (segment.match(/\d/g) || []).length;
  const letterCount = (segment.match(/[a-z]/gi) || []).length;
  if (digitCount < 2 || letterCount < 3) return false;
  const digitRuns = segment.match(/\d+/g) || [];
  const longestDigitRun = Math.max(0, ...digitRuns.map((r) => r.length));
  // A single long digit run reads as a meaningful number (a SKU, a year, a
  // phone extension) a human chose on purpose, not random noise.
  if (longestDigitRun >= 6) return false;
  return true;
}

export function sqsChecks(ctx: AuditContext): CheckResult[] {
  const out: CheckResult[] = [];
  if (!ctx.squarespace.isSquarespace) return out;

  const pages = ctx.htmlPages;
  const N = Math.max(1, pages.length);
  const home = ctx.homepage;
  const sqs = ctx.squarespace;
  const ctxObj = sqs.context;

  /* ---------------- version ---------------- */
  if (sqs.version === '7.0') {
    out.push(
      fail(
        finding({
          id: 'SQS-001',
          category: 'sqs',
          severity: 'medium',
          title: 'Your site is still on Squarespace 7.0',
          detail:
            'Squarespace 7.0 sites are locked to their original template family and cannot use Fluid Engine, the current section layouts, or most new design features as they ship. Squarespace still supports 7.0, but every new capability lands on 7.1 first, and a 7.0 site cannot switch template family without a rebuild.',
          evidence: [
            { label: 'Template version', value: `7.0${sqs.templateFamily ? ` (${sqs.templateFamily})` : ''}` },
            { label: 'Detection confidence', value: `${sqs.versionConfidence}%` },
          ],
          affected: 1,
          applicable: 1,
          effort: 'project',
        }),
        1
      )
    );
  } else if (sqs.version === '7.1') {
    out.push(pass('SQS-001', 'sqs', 'medium', 1, 'Your site runs on Squarespace 7.1, the current platform version'));
  }

  /* ---------------- editor mix ---------------- */
  if (sqs.version === '7.1' && sqs.editor.classic > 0 && sqs.editor.fluid === 0) {
    out.push(
      fail(
        finding({
          id: 'SQS-002',
          category: 'sqs',
          severity: 'low',
          title: 'Your homepage sections still use the Classic Editor',
          detail:
            'Every section on the homepage uses the older Classic Editor rather than Fluid Engine. Fluid Engine gives you independent control of mobile layout, with Classic Editor sections, the mobile view is whatever the automatic stacking produces.',
          evidence: [
            { label: 'Classic Editor sections', value: String(sqs.editor.classic) },
            { label: 'Fluid Engine sections', value: String(sqs.editor.fluid) },
          ],
          urls: [home.url],
          affected: sqs.editor.classic,
          applicable: sqs.editor.classic + sqs.editor.fluid,
          squarespacePath: 'Edit the page → hover a section → "Edit section" → switch to Fluid Engine',
          effort: 'medium',
        }),
        sqs.editor.classic + sqs.editor.fluid
      )
    );
  } else if (sqs.version === '7.1' && sqs.editor.fluid > 0) {
    out.push(pass('SQS-002', 'sqs', 'low', 1, 'Your sections use Fluid Engine, giving you full control of the mobile layout'));
  }

  /* ---------------- default favicon ---------------- */
  const homeHasDefaultFavicon = ctx.homepageHtml.includes(DEFAULT_FAVICON);
  if (homeHasDefaultFavicon) {
    out.push(
      fail(
        finding({
          id: 'SQS-003',
          category: 'sqs',
          severity: 'low',
          title: 'Your site still uses the default Squarespace favicon',
          detail:
            'The little icon in the browser tab is the Squarespace placeholder. It is a two-minute change and it is visible in every tab, bookmark and search result a visitor sees.',
          evidence: [{ label: 'Favicon URL', value: `https://${DEFAULT_FAVICON}` }],
          affected: 1,
          applicable: 1,
          squarespacePath: 'Design → Browser Icon, upload a square PNG at least 100×100px',
          effort: 'quick',
        }),
        1
      )
    );
  } else {
    out.push(pass('SQS-003', 'sqs', 'low', 1, 'You have a custom browser icon'));
  }

  /* ---------------- apple touch icon ---------------- */
  const hasAppleTouchIcon = /<link[^>]+rel=["']apple-touch-icon["']/i.test(ctx.homepageHtml);
  if (!hasAppleTouchIcon) {
    out.push(
      fail(
        finding({
          id: 'SQS-015',
          category: 'sqs',
          severity: 'low',
          title: 'No apple-touch-icon is set',
          detail:
            'Without an apple-touch-icon, an iPhone or iPad user who adds your site to their home screen gets a plain screenshot thumbnail instead of your icon. Minor, but cheap to fix and permanently visible on their home screen.',
          evidence: [{ label: 'apple-touch-icon link tag', value: 'not found on homepage' }],
          affected: 1,
          applicable: 1,
          squarespacePath: 'Design → Browser Icon usually covers this on modern templates; if not, add a <link rel="apple-touch-icon"> via Settings → Advanced → Code Injection → Header',
          effort: 'quick',
        }),
        1,
        { unscored: true }
      )
    );
  } else {
    out.push(pass('SQS-015', 'sqs', 'low', 1, 'An apple-touch-icon is set for iOS home-screen bookmarking'));
  }

  /* ---------------- non-custom domain ---------------- */
  const baseUrl: string = String(ctxObj?.website?.baseUrl || '');
  if (/^https?:\/\/[a-z0-9-]+\.squarespace\.com\/?$/i.test(baseUrl) || /\.squarespace\.com$/i.test(new URL(ctx.origin).hostname)) {
    out.push(
      fail(
        finding({
          id: 'SQS-004',
          category: 'sqs',
          severity: 'high',
          title: 'Your site runs on a squarespace.com address rather than your own domain',
          detail:
            'A built-in squarespace.com subdomain looks unfinished to customers, cannot be used on business cards convincingly, and means any search authority you build belongs to that subdomain rather than to a domain you own.',
          evidence: [{ label: 'Site address', value: baseUrl || ctx.origin }],
          affected: 1,
          applicable: 1,
          squarespacePath: 'Settings → Domains → Use a domain I own (or register one through Squarespace)',
          effort: 'quick',
        }),
        1
      )
    );
  } else {
    out.push(pass('SQS-004', 'sqs', 'high', 1, 'Your site runs on your own custom domain'));
  }

  /* ---------------- default title format ---------------- */
  const siteTitle = String(ctxObj?.website?.siteTitle || '');
  const collectionTitleFormat = ctxObj?.websiteSettings?.collectionTitleFormat;
  if (siteTitle && !collectionTitleFormat) {
    const defaulted = pages.filter((p) => {
      if (!p.title) return false;
      const t = p.title.replace(/\s+/g, ' ').trim();
      return t === siteTitle || /^.+\s+[,--]\s+.+$/.test(t) === false ? t === siteTitle : false;
    });
    if (defaulted.length) {
      out.push(
        fail(
          finding({
            id: 'SQS-006',
            category: 'sqs',
            severity: 'medium',
            title: 'Page titles fall back to your site name instead of describing the page',
            detail:
              'When no SEO title is set, Squarespace uses the page name and site title. Those defaults rarely contain the words your customers actually type into Google.',
            evidence: defaulted.slice(0, 3).map((p) => ({ label: pathOf(p.url), value: `"${truncate(p.title, 70)}"`, url: p.url })),
            urls: defaulted.map((p) => p.url),
            affected: defaulted.length,
            applicable: N,
            squarespacePath: 'Pages → page settings (gear icon) → SEO → SEO Title',
            effort: 'quick',
          }),
          N
        )
      );
    } else {
      out.push(pass('SQS-006', 'sqs', 'medium', N));
    }
  }

  /* ---------------- /home duplicate ---------------- */
  const homeDup = ctx.probes.homeDuplicate;
  if (homeDup && homeDup.status >= 200 && homeDup.status < 300) {
    const inSitemap = ctx.sitemap.urls.some((u) => /\/home\/?$/.test(u.loc));
    out.push(
      fail(
        finding({
          id: 'SQS-007',
          category: 'sqs',
          severity: inSitemap ? 'medium' : 'low',
          title: 'Your homepage is also reachable at /home',
          detail:
            'Squarespace serves the homepage both at your root address and at its page slug, usually /home. That produces two indexable URLs with identical content.' +
            (inSitemap ? ' Your sitemap actively advertises the duplicate to search engines.' : ''),
          evidence: [
            { label: 'Duplicate URL', value: `${ctx.origin}/home, HTTP ${homeDup.status}`, url: `${ctx.origin}/home` },
            { label: 'Listed in sitemap', value: inSitemap ? 'yes' : 'no' },
          ],
          urls: [`${ctx.origin}/home`],
          affected: 1,
          applicable: 1,
          squarespacePath: 'Pages → Homepage settings → change the URL slug, or add a URL Mapping under Settings → Developer Tools → URL Mappings: /home -> / 301',
          effort: 'quick',
        }),
        1
      )
    );
  } else {
    out.push(pass('SQS-007', 'sqs', 'low', 1));
  }

  /* ---------------- auto-generated slugs ---------------- */
  const garbage = ctx.sitemap.urls.filter((u) => {
    const path = new URL(u.loc, ctx.origin).pathname;
    const lastSegment = path.replace(/\/$/, '').split('/').pop() || '';
    return looksAutoGenerated(lastSegment);
  });
  if (ctx.sitemap.urls.length >= 5) {
    if (garbage.length) {
      out.push(
        fail(
          finding({
            id: 'SQS-008',
            category: 'sqs',
            severity: 'low',
            title: `${count(garbage.length, 'page')} ${verb(garbage.length, 'has', 'have')} auto-generated gibberish URLs`,
            detail:
              'Squarespace generates a random slug when a page or post is duplicated or created without a title. These URLs are unmemorable, unshareable and carry no keyword value.',
            evidence: garbage.slice(0, 3).map((u) => ({ label: 'URL', value: new URL(u.loc, ctx.origin).pathname, url: u.loc })),
            urls: garbage.map((u) => u.loc),
            affected: garbage.length,
            applicable: ctx.sitemap.urls.length,
            squarespacePath: 'Pages → page settings (gear icon) → General → URL Slug (set a URL Mapping redirect from the old slug)',
            effort: 'quick',
          }),
          ctx.sitemap.urls.length,
          { gamma: 1.0 }
        )
      );
    } else {
      out.push(pass('SQS-008', 'sqs', 'low', ctx.sitemap.urls.length, 'Your page URLs are clean and readable'));
    }
  }

  /* ---------------- category / tag index bloat ---------------- */
  const archiveUrls = ctx.sitemap.urls.filter((u) => /\/(category|tag)\//i.test(u.loc));
  if (archiveUrls.length >= 5) {
    out.push(
      fail(
        finding({
          id: 'SQS-009',
          category: 'sqs',
          severity: 'low',
          title: `${count(archiveUrls.length, 'category and tag archive page')} ${verb(archiveUrls.length, 'is', 'are')} in your sitemap`,
          detail:
            'Squarespace automatically creates an archive page for every blog category and tag, and lists them all in the sitemap. These are thin, near-duplicate pages that compete with the posts themselves for attention from search engines.',
          evidence: archiveUrls.slice(0, 3).map((u) => ({ label: 'Archive page', value: new URL(u.loc, ctx.origin).pathname, url: u.loc })),
          urls: archiveUrls.map((u) => u.loc),
          affected: archiveUrls.length,
          applicable: Math.max(1, ctx.sitemap.urls.length),
          squarespacePath: 'Blog page settings → SEO → hide category and tag pages from search engines',
          effort: 'quick',
        }),
        Math.max(1, ctx.sitemap.urls.length),
        { gamma: 1.0 }
      )
    );
  } else {
    out.push(pass('SQS-009', 'sqs', 'low', 1));
  }

  /* ---------------- member areas indexability ---------------- */
  // A site with gated content genuinely has different SEO/indexability
  // trade-offs than a fully public one — you often *want* member-only pages
  // excluded from search (AUDIT-OF-THE-AUDIT.md, Step 4, item 6). We don't
  // have a reliable per-page signal for "this specific page is behind the
  // member gate" (that would need session-aware crawling this engine
  // deliberately doesn't do), so rather than guess at which noindexed pages
  // are member content and silently change TECH-030's scoring, this is a
  // separate, always-informational note giving the site owner the context to
  // interpret TECH-030 correctly themselves.
  if (sqs.features.memberAreas) {
    const anyNoindexed = pages.some((p) => /\bnoindex\b/.test(p.metaRobots) || /\bnoindex\b/.test(p.xRobotsTag));
    out.push(
      pass(
        'SQS-016',
        'sqs',
        'low',
        1,
        anyNoindexed
          ? 'Member Areas is active on this site. If any pages flagged as noindexed above are member-gated content, excluding them from search is normal and often intentional, not a fault'
          : 'Member Areas is active on this site'
      )
    );
  }

  /* ---------------- password-protected pages ---------------- */
  if (ctxObj?.collection?.passwordProtected) {
    out.push(
      fail(
        finding({
          id: 'SQS-010',
          category: 'sqs',
          severity: 'medium',
          title: 'A password is set on a public page',
          detail:
            'This page requires a password, so neither visitors nor search engines can see its content.',
          evidence: [{ label: 'Collection', value: String(ctxObj.collection.title || ctxObj.collection.urlId || 'unknown') }],
          affected: 1,
          applicable: 1,
          squarespacePath: 'Pages → page settings → Password, remove the password',
          effort: 'quick',
        }),
        1
      )
    );
  }

  /* ---------------- developer mode ---------------- */
  if (sqs.features.devMode) {
    out.push(
      fail(
        finding({
          id: 'SQS-011',
          category: 'sqs',
          severity: 'medium',
          title: 'Your site is running in Squarespace Developer Mode',
          detail:
            'Developer Mode gives full template control but permanently disables the visual style editor and blocks all automatic template updates from Squarespace. Any change now requires a developer.',
          evidence: [{ label: 'Detected from', value: 'no template tweak classes and no platform site bundle in the page source' }],
          affected: 1,
          applicable: 1,
          effort: 'project',
        }),
        1
      )
    );
  } else {
    out.push(pass('SQS-011', 'sqs', 'medium', 1));
  }

  /* ---------------- commerce without product markup ---------------- */
  if (sqs.features.commerce) {
    const hasProduct = pages.some((p) => p.schemaTypes.includes('Product'));
    if (!hasProduct) {
      out.push(
        fail(
          finding({
            id: 'SQS-012',
            category: 'sqs',
            severity: 'medium',
            title: 'Your store pages carry no product structured data',
            detail:
              'Squarespace Commerce is active but none of the crawled pages expose Product markup. Without it, your items cannot show prices, availability or review stars in Google results.',
            evidence: [{ label: 'Commerce detected', value: 'yes' }, { label: 'Product schema found', value: 'no' }],
            affected: 1,
            applicable: 1,
            effort: 'medium',
          }),
          1
        )
      );
    } else {
      out.push(pass('SQS-012', 'sqs', 'medium', 1, 'Your products expose structured data for rich search results'));
    }
  }

  /* ---------------- per-product commerce completeness ---------------- */
  // SQS-012 above only checks whether Product schema exists anywhere on the
  // site. It says nothing about whether each individual product page is
  // actually complete — missing an image, missing a price, or missing a
  // description entirely undermines both conversion and rich-result
  // eligibility on a per-product basis (AUDIT-OF-THE-AUDIT.md, Step 7, P1).
  if (sqs.features.commerce) {
    const productPages = pages.filter((p) => p.pageType === 'product' || p.schemaTypes.includes('Product'));
    if (productPages.length) {
      const incomplete: Array<{ url: string; missing: string[] }> = [];
      for (const p of productPages) {
        const missing: string[] = [];
        let hasImage = false;
        let hasPrice = false;
        let hasDescription = false;
        for (const block of p.jsonLd) {
          const walk = (n: any, depth = 0) => {
            if (!n || typeof n !== 'object' || depth > 5) return;
            if (Array.isArray(n)) return n.forEach((x) => walk(x, depth + 1));
            const t = n['@type'];
            const types = Array.isArray(t) ? t : [t];
            if (types.some((x) => String(x) === 'Product')) {
              if (n.image && (typeof n.image === 'string' ? n.image.trim() : true)) hasImage = true;
              const offers = n.offers;
              const offerList = Array.isArray(offers) ? offers : offers ? [offers] : [];
              if (offerList.some((o: any) => o && (o.price || o.lowPrice))) hasPrice = true;
              if (typeof n.description === 'string' && n.description.trim().length >= 20) hasDescription = true;
            }
            for (const v of Object.values(n)) if (v && typeof v === 'object') walk(v, depth + 1);
          };
          walk(block.parsed);
        }
        // Fall back to the page's own images if schema didn't declare one.
        if (!hasImage && p.images.some((i) => i.src && !/^data:/.test(i.src))) hasImage = true;
        if (!hasImage) missing.push('product image');
        if (!hasPrice) missing.push('price');
        if (!hasDescription) missing.push('description');
        if (missing.length) incomplete.push({ url: p.url, missing });
      }
      if (incomplete.length) {
        out.push(
          fail(
            finding({
              id: 'SQS-014',
              category: 'sqs',
              severity: 'medium',
              confidence: 'heuristic',
              title: `${count(incomplete.length, 'product page')} ${verb(incomplete.length, 'is', 'are')} missing basic product information`,
              detail:
                'We checked each product page for an image, a price and a real description, the minimum a shopper or a shopping-focused AI assistant needs to evaluate a product. Missing any of these also disqualifies the page from Google\'s product rich results.',
              evidence: incomplete.slice(0, 4).map((i) => ({
                label: pathOf(i.url),
                value: `missing: ${i.missing.join(', ')}`,
                url: i.url,
              })),
              urls: incomplete.map((i) => i.url),
              affected: incomplete.length,
              applicable: productPages.length,
              squarespacePath: 'Commerce → Inventory → open the product → fill in the image, price and description fields',
              effort: 'medium',
            }),
            productPages.length,
            { gamma: 1.0 }
          )
        );
      } else {
        out.push(pass('SQS-014', 'sqs', 'medium', productPages.length, 'Your product pages carry a complete image, price and description'));
      }
    } else {
      out.push(na('SQS-014', 'sqs', 'medium'));
    }
  }

  /* ---------------- blog SEO settings ---------------- */
  // SQS-009 above flags the *symptom* — category/tag archive pages bloating
  // the sitemap — without checking whether the underlying "hide archive
  // pages from search" setting exists to fix it at the source
  // (AUDIT-OF-THE-AUDIT.md, Step 4, item 4). Only checked when an archive
  // page happens to have been crawled (the crawler prioritises real content
  // over auto-generated archive pages, so this will often be not-applicable
  // on a budget-limited crawl) — that is a real coverage limit, not a bug, so
  // it degrades to `na` rather than guessing.
  const crawledArchivePages = pages.filter((p) => /\/(category|tag)\//i.test(p.url));
  const indexableArchives = crawledArchivePages.filter(
    (p) => !/\bnoindex\b/.test(p.metaRobots) && !/\bnoindex\b/.test(p.xRobotsTag)
  );
  if (crawledArchivePages.length) {
    if (indexableArchives.length) {
      out.push(
        fail(
          finding({
            id: 'SQS-017',
            category: 'sqs',
            severity: 'low',
            title: 'Category and tag archive pages are not excluded from search',
            detail:
              'These auto-generated pages are thin, near-duplicate listings that compete with your actual posts for search attention. Squarespace has a dedicated setting to exclude them without deleting them.',
            evidence: indexableArchives.slice(0, 3).map((p) => ({ label: pathOf(p.url), value: 'indexable', url: p.url })),
            urls: indexableArchives.map((p) => p.url),
            affected: indexableArchives.length,
            applicable: crawledArchivePages.length,
            squarespacePath: 'Blog page settings → SEO → hide category and tag pages from search engines',
            effort: 'quick',
          }),
          crawledArchivePages.length
        )
      );
    } else {
      out.push(pass('SQS-017', 'sqs', 'low', crawledArchivePages.length, 'Category and tag archive pages are excluded from search'));
    }
  } else {
    out.push(na('SQS-017', 'sqs', 'low'));
  }

  // Blog post URL date format (year/month prefix vs. flat slug). Neither
  // format is objectively correct, this is reported as information, not
  // scored either way — but it's worth surfacing since changing it later
  // breaks every existing post URL.
  const blogPostPages = pages.filter((p) => p.pageType === 'blog-post');
  if (blogPostPages.length) {
    const datedUrls = blogPostPages.filter((p) => {
      try {
        return /\/\d{4}\/\d{1,2}\//.test(new URL(p.url).pathname);
      } catch {
        return false;
      }
    });
    out.push(
      pass(
        'SQS-018',
        'sqs',
        'low',
        1,
        datedUrls.length === blogPostPages.length
          ? 'Your blog post URLs include a year/month prefix'
          : 'Your blog post URLs use flat slugs without a date prefix'
      )
    );
  }
  // Excerpt configuration (whether the blog index shows a summary or the full
  // post) is not included here: distinguishing "an intentionally short
  // excerpt" from "a post that is just short" is not reliably determinable
  // from the rendered markup alone, and guessing risks a confidently wrong
  // finding of exactly the kind this review was meant to catch. Deferred
  // rather than implemented on a guess.

  /* ---------------- unused built-in features ---------------- */
  // Reframed as informational and unscored: an announcement bar and a
  // promotional popup are legitimate UX/conversion trade-offs, not free wins
  // with no downside (an aggressive popup is a well-documented conversion
  // killer and a Google mobile-interstitial ranking risk), and plenty of
  // well-run sites deliberately skip both. This was the only check in the
  // tool built around feature-utilization rather than a measurable problem
  // (AUDIT-OF-THE-AUDIT.md, Step 3, SQS-013), so it no longer counts toward
  // the Squarespace Setup score.
  const unused: string[] = [];
  const realForms = pages.reduce((a, p) => a + p.forms.length, 0);
  if (realForms === 0) unused.push('Form Blocks (no lead capture form found on any page)');
  if (!sqs.features.announcementBar) unused.push('Announcement Bar (a free site-wide promotion strip)');
  if (!sqs.features.popupOverlay) unused.push('Promotional Pop-up (built-in email capture)');
  if (unused.length >= 2) {
    out.push(
      fail(
        finding({
          id: 'SQS-013',
          category: 'sqs',
          severity: 'low',
          title: 'You are not using some built-in Squarespace features',
          detail:
            'These are included in your existing plan, need no plugin and no code, and each one is a lead-capture or promotion tool worth considering. Whether to use them is a real trade-off, not a fault: an announcement bar or popup can also hurt conversion or mobile UX if overused.',
          evidence: unused.map((u) => ({ label: 'Unused feature', value: u })),
          affected: unused.length,
          applicable: 3,
          squarespacePath: 'Marketing → Promotional Pop-Up, and Website → Website Tools → Announcement Bar',
          effort: 'quick',
        }),
        3,
        { gamma: 1.0, unscored: true }
      )
    );
  } else {
    out.push(pass('SQS-013', 'sqs', 'low', 3));
  }

  return out;
}
