/**
 * Embeds the PDF typefaces as base64 data URLs.
 *
 * @react-pdf/renderer takes a string for `src`: a URL, a filesystem path, or a
 * base64 data URL. A URL would make every PDF depend on Google Fonts being
 * reachable, and a filesystem path depends on the bundler tracing a file it
 * cannot see being imported, so the data URL is the only option that always
 * works on a serverless function.
 */
const fs = require('fs');
const files = {
  SERIF_REGULAR: 'Newsreader-Regular.ttf',
  SERIF_SEMIBOLD: 'Newsreader-SemiBold.ttf',
  SANS_REGULAR: 'Inter-Regular.ttf',
  SANS_SEMIBOLD: 'Inter-SemiBold.ttf',
  MONO_REGULAR: 'IBMPlexMono-Regular.ttf',
};
let out =
  '/**\n' +
  ' * Typefaces for the PDF, embedded as base64 data URLs.\n' +
  ' * Generated by scripts/fetch-fonts.sh. Do not edit by hand.\n' +
  ' * Source: Google Fonts, SIL Open Font License 1.1.\n' +
  ' */\n\n';
for (const [k, f] of Object.entries(files)) {
  const b = fs.readFileSync('src/lib/pdf/fonts/' + f).toString('base64');
  out += `export const ${k} =\n  'data:font/truetype;base64,${b}';\n\n`;
}
fs.writeFileSync('src/lib/pdf/fonts.ts', out);
console.log('embedded', Object.keys(files).length, 'fonts');
