/* eslint-disable @next/next/no-img-element */
import Link from 'next/link';
import { ROUTES } from './routes';

export function IntegrationsSection() {
  return (
    <section className="integration section" id="integrations"><div className="shell integration-grid"><div className="integration-copy reveal"><div className="kicker">Send every lead somewhere useful</div><h2>Your stack, connected.</h2><p>Sync outcomes, scores and answers to the tools your team already uses. Pro unlocks all integrations and webhooks.</p><Link href={ROUTES.integrations} className="button ghost">See integration details <span className="arr">↗</span></Link></div><div className="reveal"><div className="integration-logos"><div className="integration-logo"><img src="https://cdn.simpleicons.org/mailchimp/111111" alt="Mailchimp logo" loading="lazy" decoding="async" /><span>Mailchimp</span></div><div className="integration-logo"><img src="https://www.google.com/s2/favicons?domain=klaviyo.com&sz=128" alt="Klaviyo logo" loading="lazy" decoding="async" /><span>Klaviyo</span></div><div className="integration-logo"><img src="https://www.google.com/s2/favicons?domain=kit.com&sz=128" alt="ConvertKit logo" loading="lazy" decoding="async" /><span>ConvertKit</span></div><div className="integration-logo"><img src="https://cdn.simpleicons.org/hubspot/FF7A59" alt="HubSpot logo" loading="lazy" decoding="async" /><span>HubSpot</span></div><div className="integration-logo"><img src="https://cdn.simpleicons.org/googlesheets/34A853" alt="Google Sheets logo" loading="lazy" decoding="async" /><span>Google Sheets</span></div><div className="integration-logo"><img src="https://cdn.simpleicons.org/zapier/FF4F00" alt="Zapier logo" loading="lazy" decoding="async" /><span>Zapier + webhooks</span></div><div className="integration-logo"><img src="https://www.google.com/s2/favicons?domain=activecampaign.com&sz=128" alt="ActiveCampaign logo" loading="lazy" decoding="async" /><span>ActiveCampaign</span></div><div className="integration-logo"><img src="https://cdn.simpleicons.org/calendly/006BFF" alt="Calendly logo" loading="lazy" decoding="async" /><span>Calendly</span></div><div className="integration-logo"><img src="https://www.google.com/s2/favicons?domain=acuityscheduling.com&sz=128" alt="Acuity Scheduling logo" loading="lazy" decoding="async" /><span>Acuity</span></div></div><p className="integration-note">Mailchimp, Klaviyo, ConvertKit, Google Sheets, Zapier and webhooks appear in the current pricing catalog. Additional connectors exist in the backend and must be checked before the public integrations page lists them as generally available.</p></div></div></section>
  );
}
