/* eslint-disable @next/next/no-img-element */
import Link from 'next/link';
import { ROUTES } from './routes';

export function TemplatesSection() {
  return (
    <section className="real-templates section" id="templates"><div className="shell"><div className="kicker reveal">Templates from the real product</div><div className="section-head reveal"><h2>Start with something that already works.</h2><p>These are pulled from the current template library, with the same photography and content used inside the builder.</p></div><div className="templates-grid"><article className="template-card big reveal"><div className="template-image"><img src="https://images.unsplash.com/photo-1519741497674-611481863552?w=1000&q=85&fit=crop" alt="Wedding ceremony from the Photography Style Quiz" loading="lazy" decoding="async" /><span className="badge">Photography</span></div><div className="template-info"><small>Lead qualification + package match</small><h3>Photography Style Quiz</h3><p>Match potential clients to the right package using style, event, budget and timeline.</p></div></article><article className="template-card reveal"><div className="template-image"><img src="https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&q=82&fit=crop" alt="Retail store from the Product Finder Quiz" loading="lazy" decoding="async" /><span className="badge">Online store</span></div><div className="template-info"><small>Product recommendation</small><h3>Product Finder Quiz</h3><p>Reduce decision fatigue and recommend a relevant product.</p></div></article><article className="template-card reveal"><div className="template-image"><img src="https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800&q=82&fit=crop" alt="Interior from the Home Style Quiz" loading="lazy" decoding="async" /><span className="badge">Interior design</span></div><div className="template-info"><small>Style discovery</small><h3>Home Style Quiz</h3><p>Capture budget, room focus and design preferences before the consultation.</p></div></article><article className="template-more reveal"><strong>+13</strong><h3>Fitness, beauty, coaching, real estate, food, travel and more.</h3><Link href={ROUTES.templates}>Browse all 16 templates ↗</Link></article></div></div></section>
  );
}
